### ISSUE TITLE
How to parse two RSS using same class with different elements

### ISSUE THREAD

**Issue by cloudjanak** [KieranMcGrady/KMXMLParser#6]

**Comment by KieranMcGrady** [comment]
If you need to parse different elements you will need to adapt the class. You could add more than the standard number of elements to KMXMLParser and then just retrieve the ones you need or create a function that allows you to specify which elements you want KMXMLParser to search for. There is currently no built in way to do what you are asking but it should be easy to adapt. If you do please feel free to submit a pull request.
